stages:
  - test
  - analysis
  - build
  - deploy

services:
- name: mysql
  alias: dbtest
- name: redis
  alias: redis

unittest:
  #image: registry.2le.net/2le/2le:base-php7-xdebug
  image: registry.2le.net/2le/2le:base-php7
  type: test
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.2le.net
    - composer install
    - make test
  artifacts:
      paths:
        - phpunit.coverage.xml
        - phpunit.report.xml

sonarqube:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: https://sonar.2le.net
    SONAR_ANALYSIS_MODE: publish
  script:
  - gitlab-sonar-scanner


build:
  image: registry.2le.net/2le/2le:base-php7
  type: build
  only:
  - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - make build

buildprod:
  image: registry.2le.net/2le/2le:base-php7
  type: build
  only:
    - prod
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - make buildprod

    
deploy:
  image: registry.2le.net/2le/2le:base-php7
  type: deploy
  only:
  - master
  script:
    - ssh -o StrictHostKeyChecking=no root@SERVER /root/PROJECT/up.sh
