stages:
  - test
  - analysis
  - build

variables:
  MYSQL_DATABASE: db
  MYSQL_ROOT_PASSWORD: pass

services:
- name: mysql:5.7
  alias: database

unittest:
  image: registry.2le.net/2le/2le:base-php7-xdebug
  type: test
  script:
    - composer install
    - bin/console doc:schem:up --force
    #- bin/console doc:fix:load -n
    - bin/phpunit --coverage-clover phpunit.coverage.xml --log-junit phpunit.report.xml
  artifacts:
      paths:
        - phpunit.coverage.xml
        - phpunit.report.xml

sonarqube:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: https://sonar.2le.net
    SONAR_ANALYSIS_MODE: publish
  script:
  - gitlab-sonar-scanner

build:
  image: registry.2le.net/2le/2le:base-php7
  type: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - make build

#deploy:
#  image: registry.2le.net/2le/2le:base-php7
#  type: deploy
#  script:
#    - ssh -o StrictHostKeyChecking=no root@SERVER /root/APPLI/up.sh
#  only:
#    - master